version: '3'

services:
    redis:
        image: bitnami/redis:4.0.14
        environment:
            - REDIS_PASSWORD=campus!junior
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data/:/data/
        hostname: redis
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"
    mariadb:
            image: 'bitnami/mariadb:latest'
            environment:
                - MARIADB_ROOT_PASSWORD=campus!junior
                - MARIADB_DATABASE=campus_junior
                - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=1000 --max_allowed_packet=256M --connect_timeout=600 --net_read_timeout=600 --net_write_timeout=600
            ports:
                - '3306:3306'
            volumes:
                - './mariadb_data:/bitnami/mariadb/data'
            hostname: mariadb
            restart: always
            logging:
                driver: "json-file"
                options:
                    max-size: "100M"
                    max-file: "3"

    app:
        image: 'gcr.io/ninth-quarter-258309/campus-junior:20200420.1'
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=dev
            - IS_MIGRATE_DB=true
        restart: always
